### ISSUE TITLE
UnicodeEncodeError when dealing with unicode column names

### ISSUE THREAD

**Issue by SzieberthAdam** [enricofer/spatialJoin#1]
```
Traceback (most recent call last):
  File "C:/Documents and Settings/ti2/.qgis2/python/plugins\spatialJoin\spatialjoin.py", line 186, in applyJoin
    self.tra.ce( exp)
  File "C:/Documents and Settings/ti2/.qgis2/python/plugins\spatialJoin\spatialjoin.py", line 45, in ce
    print string
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 15: ordinal not in range(128)
```

**Comment by enricofer** [comment]
Well Done! Thank you!
Please submit Pull Request including debug trace disabled setting line 42 self.trace = None

**Comment by SzieberthAdam** [comment]
You welcome! I submit that immediately.
